CREATE TABLE TBL_EMPLOYEE
(
EMPLOYEE_NO BIGINT PRIMARY KEY,
BIRTH_DATE DATE,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
GENDER VARCHAR(50),
HIREDATE DATE
);

CREATE TABLE TBL_DEPARTMENTS
(
DEPARTMENT_NO CHAR(10) PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(40)
);


CREATE TABLE TBL_EMP_TITLE
(
EMPLOYEE_NO BIGINT,
TITLE VARCHAR(50),
FROM_DATE DATE,
TO_DATE DATE,
FOREIGN KEY(EMPLOYEE_NO) REFERENCES TBL_EMPLOYEE(EMPLOYEE_NO)
);

CREATE TABLE TBL_EMP_SALARY
(
EMPLOYEE_NO BIGINT,
TITLE VARCHAR (50),
FROM_DATE DATE,
TO_DATE DATE,
FOREIGN KEY(EMPLOYEE_NO) REFERENCES TBL_EMPLOYEE(EMPLOYEE_NO)
);


CREATE TABLE TBL_DEPT_EMP 
(
EMPLOYEE_NO BIGINT,
DEPARTMENT_NO CHAR(10),
FROM_DATE DATE,
TO_DATE DATE,
FOREIGN KEY(EMPLOYEE_NO) REFERENCES TBL_EMPLOYEE(EMPLOYEE_NO),
FOREIGN KEY(DEPARTMENT_NO) REFERENCES TBL_DEPARTMENTS(DEPARTMENT_NO)
);


CREATE TABLE TBL_DEPARTMENT_MANAGER 
(
DEPARTMENT_NO CHAR(10),
EMPLOYEE_NO BIGINT,
FROM_DATE DATE,
TO_DATE DATE,
FOREIGN KEY(DEPARTMENT_NO) REFERENCES TBL_DEPARTMENTS(DEPARTMENT_NO),
FOREIGN KEY(EMPLOYEE_NO) REFERENCES TBL_EMPLOYEE(EMPLOYEE_NO)
);